# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for Gradle
- package-ecosystem: gradle
  # Look for a `build.gradle` in the `root` directory
  directory: "/"
  # Check for updates every day (weekdays)
  schedule:
    interval: daily
  open-pull-requests-limit: 10
