component_depth: 2
languages:
  - name: java
    production:
      include:
        - /app/src/main/java/puscas/mobilertapp/.*\.java
    test:
      include:
        - /app/src/androidTest/java/puscas/mobilertapp/.*\.java
        - /app/src/test/java/puscas/mobilertapp/.*\.java

  - name: cpp
    production:
      include:
        - /app/.*\.cpp
      exclude:
        - /app/Unit_Testing/.*
        - /app/System_dependent/Native/Qt/build.*/.*
        - /build.*/.*
        - /app/third_party/.*
    test:
      include:
        - /app/Unit_Testing/.*\.cpp

  - name: script
    production:
      include:
        - /scripts/.*\.sh
