# Opt in using the repository setting "Build config validation"
version: ~> 1.0

# language: android, c, clojure, cpp, crystal, csharp, d, dart, elixir, elm,objective-c, ruby
language: cpp

# Git
git:
  submodules: false

# arch: amd64, arm64, arm64-graviton2, ppc64le, s390x
# os: linux, osx, windows
#os:
#- linux
#- osx
#- windows

# dist: 20.04: focal | 18.04: bionic | 16.04: xenial | 14.04: trusty | 12.04: precise | server-2016
#dist: bionic

# compiler: gcc, clang
#compiler:
#- gcc
#- clang


_shared_job: &shared_job
  script: echo "shared script config";

jobs:
  include:

  - stage: Build
    os: linux
    dist: bionic
    arch:
    - amd64
    - arm64
    - arm64-graviton2
    - ppc64le
    - s390x
    compiler:
    - gcc
    - clang
    before_install:
    - sudo apt-get update;
    - sudo apt-cache search libomp-dev;
    - sudo apt-cache search openmp;
    - sudo apt-cache search omp;
    - sudo apt-get install --no-install-recommends -y libomp-dev || true;
    - sudo apt-get install --no-install-recommends -y libiomp-dev || true;
    - sudo apt-get install --no-install-recommends -y qt5-default;
    - export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH};
    - sudo find / -name "omp.h" || true;
    - sudo find / -name "*omp*" || true;
    - export CPLUS_INCLUDE_PATH=/usr/lib/gcc/s390x-linux-gnu/7/include:${CPLUS_INCLUDE_PATH};
    - export LIBRARY_PATH=${LIBRARY_PATH};
    install:
    - mkdir -p build_native;
    - cd build_native;
    - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Debug ../app/;
    - cmake --build .;
    before_script:
    - ls -laR;
    script:
    - ./bin/UnitTestsd;
    after_script:
    - ls -laR;
    after_success:
    - ls -laR;
    after_failure:
    - ls -laR;
    <<: *shared_job

  - stage: Build
    os: osx
    arch:
    - amd64
    - arm64
    - arm64-graviton2
    - ppc64le
    - s390x
    compiler:
    - gcc
    - clang
    before_install:
    - brew update > update.log;
    - brew install libomp > install_libomp.log;
    - brew tap cartr/qt4 > install_qt4.log;
    - brew uninstall --force openssl@1.0 > uninstall_openssl.log;
    - brew install openssl@1.0 > install_openssl.log;
    - brew install qt@4 > install_qt4.log;
    - brew install qt > install_qt.log;
    - export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH};
    - sudo find / -name "omp.h" || true;
    - sudo find / -name "*omp.*" || true;
    - export CPLUS_INCLUDE_PATH=/usr/lib/gcc/s390x-linux-gnu/7/include:${CPLUS_INCLUDE_PATH};
    - export LIBRARY_PATH=${LIBRARY_PATH};
    install:
    - mkdir -p build_native;
    - cd build_native;
    - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Debug ../app/;
    - cmake --build .;
    before_script:
    - ls -laR;
    script:
    - ./bin/UnitTestsd;
    after_script:
    - ls -laR;
    after_success:
    - ls -laR;
    after_failure:
    - ls -laR;
    <<: *shared_job
