language: cpp
os: linux
dist: bionic
compiler:
  - gcc

git:
  submodules: false

before_install:
  - sudo apt-get update && sudo apt-get install -y libqt4-dev

install:
  - mkdir build_native
  - cd build_native
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Debug ../app/
  - make

script:
  - ./bin/UnitTestsd

after_success:
  - lcov --capture --base-directory . --directory . --no-external --output-file coverage.info
  - genhtml coverage.info --output-directory code_coverage_report
  - bash <(curl -s https://codecov.io/bash) -t 717e75e2-b149-4997-adb4-a3fa1bde237f
