use tokio::{
    io::{AsyncBufReadExt, AsyncWriteExt, BufReader},
    net::TcpListener,
    sync::broadcast,
};

use warp::Filter;
use std::{collections::HashMap};
use std::{time::Duration};
use std::sync::atomic::{AtomicBool, Ordering};
use image::{ImageBuffer, Rgb};
use base64::{encode};

// ----- Ownership rules -----
// 1. Each value in Rust has a variable that's called its owner.
// 2. There can only be one owner at a time.
// 3. When the owner goes out of scope, the value will be dropped.

// ----- The Rules of References.
// 1. At any given time, you can have either one mutable reference
// or any number of immutable references.
// 2. References must always be valid.

#[link(name = "cpp", kind = "dylib")]
extern "C" {
    fn say_hello();
}


# [tokio::main]
async fn main() {
    unsafe {
        say_hello();
    }

    println!("Hello, world!");

    let tokio_runtime = tokio::runtime::Builder::new_multi_thread()
        .thread_keep_alive(Duration::from_secs(60))
        .enable_all()
        .build()
        .unwrap();

    let thread_http_server = tokio_runtime.spawn(async move {
        http_server().await;
    });

    thread_http_server.await.unwrap();
}

fn generate_bitmap() -> String {
    // Create an image of 100x100 pixels with a red square in the center
    let imgx = 100;
    let imgy = 100;
    let mut imgbuf = ImageBuffer::new(imgx, imgy);

    for (x, y, pixel) in imgbuf.enumerate_pixels_mut() {
        let red = if x > 25 && x < 75 && y > 25 && y < 75 { 255 } else { 0 };
        *pixel = Rgb([red, 0, 0]);
    }

    // Convert image to PNG in bytes
    let mut buf = Vec::new();
    image::codecs::png::PngEncoder::new(&mut buf)
        .encode(&imgbuf, imgx, imgy, image::ColorType::Rgb8)
        .unwrap();

    // Convert bytes to string  in Base64
    encode(&buf)
}

async fn hello(_query: HashMap<String, String>) -> Result<impl warp::Reply, warp::Rejection> {
    let bitmap_base64 = generate_bitmap();
    let html = format!(r#"
        <!DOCTYPE html>
        <html>
        <head>
            <title>Local bitmap in HTML</title>
        </head>
        <body>
            <h1>Bitmap image generated by Rust</h1>
            <img src="data:image/png;base64,{}" alt="Bitmap">
        </body>
        </html>
    "#, bitmap_base64);

    Ok(warp::reply::html(html))
}

async fn http_server() {
    println!("started http_server");
    // GET /hello/warp => 200 OK with body "Hello, warp!"
    // https://docs.rs/warp/latest/warp/macro.path.html
    // The path! macro automatically assumes the path should include an end() filter.
    // To build up a path filter prefix, such that the end() isn’t included, use the / .. syntax.
    let hello = warp::get()
        .and(warp::path("hello"))
        .and(warp::query::<HashMap<String, String>>())
        .and(warp::path::end())
        .and_then(hello);

    warp::serve(hello)
        .run(([127, 0, 0, 1], 3030))
        .await;

    println!("finished http_server");
}
