name: C++ Google Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Prepare Environment
      env:
        CC: gcc
        CXX: g++
        QT_ACCESSIBILITY: 1
      run: mkdir build_native

    - name: Install Ubuntu Dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtk2.0-dev libqt4-dev

    - name: Run CMake
      if: success()
      working-directory: build_native
      run: cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Debug -ENABLE_COVERAGE_ALL=On ../app/

    - name: Run Make
      if: success()
      working-directory: build_native
      run: make

    - name: Run Google Test
      if: success()
      working-directory: build_native/bin
      run: ./GoogleTestd
