name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # every 5 min
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '*'
    - '**/**'
    - '!.github/workflows/renovate.yml'
    - '!renovate.json'

permissions: {}

defaults:
  run:
    shell: sh
    working-directory: .

concurrency:
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: true

# Default environment variables.
env:
  GITHUB_STEP_TIMEOUT_SMALL: 4
  GITHUB_STEP_TIMEOUT_MEDIUM: 10
  GITHUB_STEP_TIMEOUT_LONG: 20

jobs:
  renovate:
    runs-on: ubuntu-24.04-arm

    # Sets permissions of the GITHUB_TOKEN to allow to delete previous jobs runs
    permissions:
      actions: write

    steps:
      - name: Checkout
        timeout-minutes: ${{ fromJSON(env.GITHUB_STEP_TIMEOUT_SMALL) }}
        if: success()
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Validate Renovate configurations
        timeout-minutes: ${{ fromJSON(env.GITHUB_STEP_TIMEOUT_SMALL) }}
        if: success()
        run: |
          npx --package renovate@latest -- renovate-config-validator renovate.json;

      - name: Delete previous Renovate runs
        timeout-minutes: ${{ fromJSON(env.GITHUB_STEP_TIMEOUT_SMALL) }}
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH=${GITHUB_REF#refs/heads/};
          echo "BRANCH: ${BRANCH}";
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}";
          echo "GITHUB_RUN_ID: ${GITHUB_RUN_ID}";
          responses_triggered=$(curl --fail-with-body -s -S \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/renovate.yml/runs?branch=${BRANCH}");
          echo 'Deleting previous Renovate runs';
          run_ids=$(printf '%s\n' "${responses_triggered}" | jq '.workflow_runs[] | select(.id != '"${GITHUB_RUN_ID}"') | .id');
          for run_id in ${run_ids}; do
            echo "Deleting run: ${run_id}";
            curl --fail-with-body -s -S -X DELETE \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${run_id}";
          done

      - name: Run Renovate
        timeout-minutes: ${{ fromJSON(env.GITHUB_STEP_TIMEOUT_SMALL) }}
        uses: renovatebot/github-action@d65ef9e20512193cc070238b49c3873a361cd50c # v46.1.1
        if: success() && github.ref == 'refs/heads/master'
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_AUTODISCOVER: 'false'
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
          RENOVATE_ALLOWED_UNSAFE_EXECUTIONS: '["gradleWrapper"]'
        with:
          # Check available parameters in: https://github.com/renovatebot/github-action/blob/master/action.yml
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          docker-user: root
