name: Reusable Android workflow

on:
  workflow_call:
    inputs:
      host_os:
        type: string
        required: true
      android_api:
        type: string
        required: true
      type:
        type: string
        required: true

permissions: {}

defaults:
  run:
    shell: sh
    working-directory: .

# Default environment variables.
env:
  GITHUB_STEP_TIMEOUT_SMALL: 4
  GITHUB_STEP_TIMEOUT_MEDIUM: 10
  GITHUB_STEP_TIMEOUT_LONG: 20

jobs:
  AndroidTests:
    name: Android tests ${{ inputs.android_api }} ${{ inputs.type }} (${{ inputs.host_os }})
    runs-on: ${{ inputs.host_os }}
    timeout-minutes: 360

    # Sets permissions of the GITHUB_TOKEN to allow delete cache and publish test results
    permissions:
      actions: write
      checks: write
      pull-requests: write # only required if `comment: true` was enabled

    steps:
      - name: Checkout
        timeout-minutes: ${{ fromJSON(env.GITHUB_STEP_TIMEOUT_MEDIUM) }}
        if: success()
        uses: actions/checkout@v5
        with:
          # Check available parameters in: https://github.com/actions/checkout/blob/main/action.yml
          lfs: true

      - name: Enable KVM group permissions
        timeout-minutes: ${{ fromJSON(env.GITHUB_STEP_TIMEOUT_SMALL) }}
        if: success() && startsWith(inputs.host_os, 'ubuntu')
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules;
          sudo udevadm control --reload-rules;
          sudo udevadm trigger --name-match=kvm;

      - name: Set Android CPU Architecture
        timeout-minutes: ${{ fromJSON(env.GITHUB_STEP_TIMEOUT_SMALL) }}
        if: success()
        run: |
          set +eu;
          MAJOR_MAC_VERSION=$(sw_vers | grep ProductVersion | cut -d ':' -f2 | cut -d '.' -f1 | tr -d '[:space:]');
          if [ "${MAJOR_MAC_VERSION}" != '' ]; then
            echo "MacOS '${MAJOR_MAC_VERSION}' detected";
          fi
          set -e;
          if ${{ endsWith(inputs.host_os, '-arm') }} = true || "${MAJOR_MAC_VERSION}" -gt 13; then
              echo 'android_arch=\"arm64-v8a\"' >> "${GITHUB_ENV}";
              echo 'android_emulator_arch=arm64-v8a' >> "${GITHUB_ENV}";
          else
            if [ "${{ inputs.android_api }}" -gt 30 ]; then
              echo 'android_arch=\"x86_64\"' >> "${GITHUB_ENV}";
              echo 'android_emulator_arch=x86_64' >> "${GITHUB_ENV}";
            else
              echo 'android_arch=\"x86\"' >> "${GITHUB_ENV}";
              echo 'android_emulator_arch=x86' >> "${GITHUB_ENV}";
            fi
          fi
          set -u;

      - name: Set CPU cores
        timeout-minutes: ${{ fromJSON(env.GITHUB_STEP_TIMEOUT_SMALL) }}
        if: success()
        run: |
          echo "android_arch: ${{ env.android_arch }}";
          echo "android_emulator_arch: ${{ env.android_emulator_arch }}";
          . scripts/helper_functions.sh && parallelizeBuild && echo "NCPU_CORES=${NCPU_CORES}" >> "${GITHUB_ENV}";
          mkdir -p ~/.android/avd/Android_Emulator_API_34.avd;

      - name: Run Android tests
        timeout-minutes: 30
        if: success() && !startsWith(inputs.host_os, 'windows')
        uses: ReactiveCircus/android-emulator-runner@1dcd0090116d15e7c562f8db72807de5e036a4ed # v2
        env:
          ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 1
          MEM_MB: 1024
        with:
          # Check available parameters in: https://github.com/ReactiveCircus/android-emulator-runner/blob/main/action.yml
          # Available CI host machines: https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories
          # Max api level for 32bit is: 30
          api-level: ${{ inputs.android_api }}
          cmake: 4.0.2
          target: google_apis
          arch: ${{ env.android_emulator_arch }}
          disable-animations: true
          disable-spellchecker: true
          channel: stable
          emulator-options: -no-metrics -no-window -accel on -cores ${{ env.NCPU_CORES }} -memory ${{ env.MEM_MB }} -cache-size 512 -partition-size 1024 -ranchu -fixed-scale -skip-adb-auth -gpu swiftshader_indirect -no-audio -no-snapshot -no-snapstorage -no-snapshot-update-time -no-snapshot-save -no-snapshot-load -no-boot-anim -camera-back none -camera-front none -netfast -wipe-data -no-sim -no-passive-gps -no-direct-adb -no-location-ui -no-hidpi-scaling -no-mouse-reposition -no-nested-warnings -verbose
          cores: ${{ env.NCPU_CORES }}
          ram-size: ${{ env.MEM_MB }}M
          heap-size: 512M
          disk-size: 10000M
          sdcard-path-or-size: 2048M
          avd-name: Android_Emulator_API_${{ inputs.android_api }}
          force-avd-creation: true
          disable-linux-hw-accel: auto
          enable-hw-keyboard: false
          emulator-boot-timeout: 400 # It can take more than 5 min to boot, and the tests can take more than 17 min to finish.
          script: |
            sh scripts/run_tests_android.sh -t ${{ inputs.type }} -r all -a ${{ inputs.android_api }} -k false -f ${{ env.android_arch }};
            echo "Run Android tests finished: ${?}";
